version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  currencyconverter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currencyconverter
    ports:
      - "8000:8000"
    environment:
      - SWOP_API_KEY=${SWOP_API_KEY}
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      - INFLUXDB_DB=metricsdb
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_ADMIN_USER=${GF_ADMIN_USER}
      - GF_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb


  frontend:
    build:
      context: ../client  
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - BACKEND_URL=http://currencyconverter:8000
    ports:
      - "8080:8080"  

volumes:
  influxdb_data:
  grafana_data:
