version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  currencyconverter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currencyconverter
    ports:
      - "8000:8000"
    environment:
      - SWOP_API_KEY=${SWOP_API_KEY}
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      - INFLUXDB_DB=metricsdb
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - backend

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_ADMIN_USER=${GF_ADMIN_USER}
      - GF_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data:
